trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: src/Fub/Fub.csproj
    arguments: -c Release
    
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: |
      src/Fub.Tests/Fub.Tests.csproj
      src/Fub.InternalTests/Fub.InternalTests.csproj
    arguments: -c Release
      
- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: 'src/Fub/Fub.csproj'
    nobuild: true
    versioningScheme: byEnvVar
    versionEnvVar: NugetPackageVersion
    