trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: src/Fub/Fub.csproj
    configuration: Release

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: |
      src/Fub.Tests/Fub.Tests.csproj
      src/Fub.InternalTests/Fub.InternalTests.csproj
    configuration: Release
      
- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: 'src/Fub/Fub.csproj'
    versioningScheme: byEnvVar
    versionEnvVar: NugetPackageVersion