trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '6.0.201'

- task: DotNetCoreCLI@2
  inputs:
    majorVersion: 6
    minorVersion: 0
    patchVersion: 201
    command: 'build'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  inputs:
    majorVersion: 6
    minorVersion: 0
    patchVersion: 201
    command: 'test'
    projects: |
      src/Fub.Tests/Fub.Tests.csproj
      src/Fub.InternalTests/Fub.InternalTests.csproj